spring.application.name=forumhub

# Datasource
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:forumhub}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.url=jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:forumhub}
spring.flyway.user=${DB_USER:postgres}
spring.flyway.password=${DB_PASSWORD:postgres}
spring.flyway.default-schema=public
spring.flyway.schemas=public
spring.flyway.create-schemas=true
spring.flyway.fail-on-missing-locations=true
spring.flyway.table=flyway_schema_history

# Logs para diagnosticar auto-configuração do Flyway
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

# JWT
jwt.secret=${JWT_SECRET:senha-secreta}
jwt.issuer=${JWT_ISSUER:ForumHub API}
jwt.expiration=${JWT_EXPIRATION:7200000}

# SpringDoc OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.persistAuthorization=true